#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=DATA_GENERATOR
#SBATCH --ntasks=1
#SBATCH --time=00:30:00
#SBATCH --output=output/processing/data_generator_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/ieai-miniproject-context-mixing/
source activate ieai-context-mix

python -m spacy download fr_core_news_md
python processing/data_generator.py
