#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=PREP_CORPUS
#SBATCH --ntasks=1
#SBATCH --time=00:15:00
#SBATCH --output=output/processing/prep_corpus_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/ieai-miniproject-context-mixing/
source activate ieai-context-mix

# python -m spacy download fr_core_news_md
python processing/mfa/preparing_corpus.py
