#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=INFERENCE_WHISPER_SMALL
#SBATCH --ntasks=1
#SBATCH --time=01:00:00
#SBATCH --output=output/inference/inference_whisper_small_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/ieai-miniproject-context-mixing/
source activate ieai-context-mix

python predicting/inference.py --MODEL_NAME whisper-small
