#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=2
#SBATCH --job-name=INFERENCE_WHISPER_BASE
#SBATCH --ntasks=1
#SBATCH --time=02:00:00
#SBATCH --output=output/inference/inference_whisper_base_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/ieai-miniproject-context-mixing/
source activate ieai-context-mix

python experiments/predicting/inference.py --MODEL_NAME whisper-base
